name: tayf_hizli_okuma
description: Gelişmiş Tayf Hızlı Okuma ve E-Kitap Eğitim Uygulaması
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  archive: ^3.4.0
  file_picker: ^8.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#1A1A24"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
